In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import ast
from sklearn.metrics import accuracy_score, classification_report
import json

In [6]:
with open('/content/drive/MyDrive/AOCD_assignment/final_data/predictions_group22_oracle.json', 'r') as f:
    oracle = json.load(f)
with open('/content/drive/MyDrive/AOCD_assignment/final_data/predictions_group22_handcrafted.json', 'r') as f:
    handcrafted = json.load(f)
with open('/content/drive/MyDrive/AOCD_assignment/final_data/predictions_group22_ngrams.json', 'r') as f:
    ngram = json.load(f)
with open('/content/drive/MyDrive/AOCD_assignment/final_data/predictions_group22_expModel.json', 'r') as f:
    lstm = json.load(f)
df=pd.read_csv('/content/drive/MyDrive/AOCD_assignment/final_data/exp_test.csv')

In [9]:
from sklearn.metrics import f1_score

session_id_hash_df = df['session_id_hash']
convert_df = df['convert']

# Extract convert values from the dictionary using session_id_hash as keys
convert_dict = [oracle.get(session_id, 0) for session_id in session_id_hash_df]
f1 = f1_score(convert_df, convert_dict)
print("F1 Score Oracle model:", f1)

convert_dict = [handcrafted.get(session_id, 0) for session_id in session_id_hash_df]
f1 = f1_score(convert_df, convert_dict)
print("F1 Score Handcrafted model:", f1)

convert_dict = [ngram.get(session_id, 0) for session_id in session_id_hash_df]
f1 = f1_score(convert_df, convert_dict)
print("F1 Score Ngram model:", f1)

convert_dict = [lstm.get(session_id, 0) for session_id in session_id_hash_df]
f1 = f1_score(convert_df, convert_dict)
print("F1 Score LSTM model:", f1)

F1 Score Oracle model: 0.8384402824685293
F1 Score Handcrafted model: 0.3375551283501075
F1 Score Ngram model: 0.47523561259274116
F1 Score LSTM model: 0.5091470134450078


In [ ]:
train=pd.read_csv("/content/drive/MyDrive/AOCD_assignment/Data/preprocessed_train.csv")
val=pd.read_csv("/content/drive/MyDrive/AOCD_assignment/Data/preprocessed_validation.csv")

In [ ]:
train["product_action_symb2"] = train["product_action_symb"].apply(lambda x: list(ast.literal_eval(x.strip('[]'))))
val["product_action_symb2"] = val["product_action_symb"].apply(lambda x: list(ast.literal_eval(x.strip('[]'))))

In [ ]:
X_train=train["product_action_symb2"]
y_train=train["convert"]
X_val=val["product_action_symb2"]
y_val=val["convert"]

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Assuming X_train is your original list of sequences
X_train_padded = pad_sequences(X_train, padding='post', dtype='float32')

# Now X_train_padded is a 2D numpy array with padded sequences


In [ ]:
X_train = [np.array(sample).flatten() for sample in X_train]
X_train = np.array(X_train_padded)


In [ ]:
X_train

[array([1, 1, 2, 1, 3, 1, 1, 1]),
 array([2, 1, 2, 1, 3]),
 array([1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 3, 2, 1, 1, 2,
        1, 3]),
 array([2, 1, 3, 3, 1]),
 array([1, 1, 1, 3, 4, 1, 4, 4, 4, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 3, 1, 2, 1]),
 array([1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2,
        2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 3, 2, 1, 1, 2, 1, 2, 1, 2,
        2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 2, 1,
        2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1]),
 array([2, 1, 2, 1, 1, 1, 1, 1, 2, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1]),
 array([1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1,
        2, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2,
        1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2,
        1, 3, 2, 1, 1, 2, 1, 2, 2, 1, 4, 3, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1,
        1, 2]),
 array([1, 1, 1, 1, 1, 1

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Assuming you have your feature matrix X_train and corresponding labels y_train
# X_train should be a 2D array where each row is a data point and each column is a feature

# Split your data into training and testing sets (optional)
# X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Standardize the data
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)

# Create and train the SVM model
model = SVC(kernel='linear', C=1.0)  # You can choose a different kernel and adjust C based on your dataset
model.fit(X_train, y_train)

# Predict on the training data
predictions = model.predict(X_train)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_train, predictions))
print("\nClassification Report:")
print(classification_report(y_train, predictions))
